#pragma config(Motor,  port2,           DriveFR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           DriveBR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LiftR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LiftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           MiniLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BallLauncher,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           DriveBL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           DriveFL,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// Other important files
//#include "Utils.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous(){
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol(){

  while (true){
 //----------------------------------- Drive -------------------------------------------------

  	motor[port2] = vexRT(Ch2);
  	motor[port3] = vexRT(Ch2);
  	motor[port8] = vexRT(Ch3);
  	motor[port9] = vexRT(Ch3);

 //----------------------------------- Lift -------------------------------------------------
		if(vexRT(Btn6U) == 1){
			setMotor(LiftR, 127);
			setMotor(LiftL, -127);
		}
		else if(vexRT(Btn6D) == 1){
			setMotor(LiftR, -127);
			setMotor(LiftL, 127);
		}
		else{
			setMotor(LiftR, 0);
			setMotor(LiftL, 0);
		}

 //----------------------------------- Minilift -------------------------------------------------
		if(vexRT(Btn5U) == 1){
			setMotor(MiniLift, -50);
		}
		else if(vexRT(Btn5D) == 1){
			setMotor(MiniLift, 50);
		}
		else{
			setMotor(MiniLift, 0);
		}

 //----------------------------------- Ball Shooter -------------------------------------------------
		if(vexRT(Btn7D) == 1){
			setMotor(BallLauncher, -127);
		}
		else{
			setMotor(BallLauncher, 0);
		}
  }
}
